# -*- coding: utf-8 -*-
"""LogRegPickl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJAqm6ErqfEJpgmhCFs0dNrsmbHXTHdl
"""

import pickle as pkl

prediction = pkl.load(open('model.pkl','rb'))
Pickl = pkl.load(open('model.pkl','rb'))

Predection = Pickl.predict([[1,1,1,2,0,0,0,1,4,0,0,0,50,1,2018,4,20, 0, 0, 0]])
Predection